In [ ]:
import numpy as np

In [ ]:
import pandas as pd

Task - 1

In [ ]:
rand = np.random.randint(0,100,size=(4,4)) #creating a rand variable to store 4x4 values of random numbers from 0 to 100

In [ ]:
rand

array([[ 2, 84, 50, 14],
       [46, 28, 67, 87],
       [40, 55, 56, 84],
       [67,  4, 13, 73]])

In [ ]:
df = pd.DataFrame(rand) #creating a dataframe with the random values stored in rand

In [ ]:
df

    0   1   2   3
0   2  84  50  14
1  46  28  67  87
2  40  55  56  84
3  67   4  13  73

Task - 2

In [ ]:
df.columns = ['Random Value 1','Random Value 2','Random Value 3','Random Value 4']   #assigning column  name to each column

In [ ]:
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0               2              84              50              14
1              46              28              67              87
2              40              55              56              84
3              67               4              13              73

Task 3

In [ ]:
df.info() #basic information on the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  4 non-null      int64
 1   Random Value 2  4 non-null      int64
 2   Random Value 3  4 non-null      int64
 3   Random Value 4  4 non-null      int64
dtypes: int64(4)
memory usage: 256.0 bytes

In [ ]:
df.describe() #descriptive statistics

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000            4.00        4.000000         4.00000
mean        38.750000           42.75       46.500000        64.50000
std         27.097048           34.50       23.416518        34.20039
min          2.000000            4.00       13.000000        14.00000
25%         30.500000           22.00       40.750000        58.25000
50%         43.000000           41.50       53.000000        78.50000
75%         51.250000           62.25       58.750000        84.75000
max         67.000000           84.00       67.000000        87.00000

Task 4

In [ ]:
df.isnull().any() #checking for anyy null value in the dataframe

Random Value 1    False
Random Value 2    False
Random Value 3    False
Random Value 4    False
dtype: bool

In [ ]:
df.dtypes  #finding the datatype of each columns

Random Value 1    int64
Random Value 2    int64
Random Value 3    int64
Random Value 4    int64
dtype: object

Task 5

In [ ]:
df.loc[:,["Random Value 2","Random Value 3"]] #using location method

   Random Value 2  Random Value 3
0              84              50
1              28              67
2              55              56
3               4              13

In [ ]:
df.iloc[:,1:3] #using indexed location method

   Random Value 2  Random Value 3
0              84              50
1              28              67
2              55              56
3               4              13